### ISSUE TITLE
git_branch_from_item issue

### ISSUE THREAD

**Issue by santi-h** [bodyshopbidsdotcom/git-scripts#178]
```
Traceback (most recent call last):
  File "/Users/dcharp/Code/git-scripts/lib/run_script.py", line 25, in <module>
    run()
  File "/Users/dcharp/Code/git-scripts/lib/run_script.py", line 11, in run
    importlib.import_module(script_name).run()
  File "/Users/dcharp/Code/git-scripts/lib/branch_from_item.py", line 12, in run
    api = PyRollbarAPI(repo)
  File "/usr/local/lib/python2.7/site-packages/rollbarapi.py", line 60, in __init__
    self._access_tokens = PyAccountRollbarAPI().get_project_access_tokens(project_name)
  File "/usr/local/lib/python2.7/site-packages/rollbarapi.py", line 44, in get_project_access_tokens
    project_id = self.get_project_id_from_name(project_name)
  File "/usr/local/lib/python2.7/site-packages/rollbarapi.py", line 38, in get_project_id_from_name
    for project in (self.call('list_projects')[0]['result'] or []):
KeyError: 'result'
```

**Comment by santi-h** [comment]
Should be handled in https://github.com/bodyshopbidsdotcom/git-scripts/issues/194
