### ISSUE TITLE
Issue: [branch_from_task] TypeError: __init__() got an un...

### ISSUE THREAD

**Issue by lluchez** [bodyshopbidsdotcom/git-scripts#251]
```
> git_branch_from_task https://www.wrike.com/open.htm?id=140702561

Traceback (most recent call last):
  File "/Users/lionelluchez/Snapsheet/Projects/bodyshopbidsdotcom/git-scripts/lib/run_script.py", line 19, in run
    importlib.import_module(script_name).run()
  File "/Users/lionelluchez/Snapsheet/Projects/bodyshopbidsdotcom/git-scripts/lib/branch_from_task.py", line 19, in run
    wrike_gateway = Wrike(data_filepath=Helper.get_data_filepath('wrike'), client_id=Helper2.get_var('WRIKE_CLIENT_ID'), client_secret=Helper2.get_var('WRIKE_CLIENT_SECRET'))
TypeError: __init__() got an unexpected keyword argument 'client_secret'
```
Using git-scripts version `0.0.0`

**Comment by lluchez** [comment]
@santi-h , did you see that issue?

**Comment by santi-h** [comment]
@lluchez I'll take a look
```
basegateway==0.12
colored==1.2.1
gitdb==0.6.4
githubgateway==0.5
GitPython==1.0.1
inflection==0.3.1
pbr==1.10.0
PyGithub==1.26.0
PyRollbarAPI==0.6
PyWrike==0.5
PyYAML==3.11
requests==2.9.1
six==1.10.0
smmap==0.9.0
stevedore==1.20.0
virtualenv==15.1.0
virtualenv-clone==0.2.6
virtualenvwrapper==4.7.2
```
