### ISSUE TITLE
Issue: [create_pr] TypeError: expected string or buffer

### ISSUE THREAD

**Issue by santi-h** [bodyshopbidsdotcom/git-scripts#254]
```
> git_create_pr

Traceback (most recent call last):
  File "/Users/santiago/scripts/git/lib/run_script.py", line 19, in run
    importlib.import_module(script_name).run()
  File "/Users/santiago/scripts/git/lib/create_pr.py", line 36, in run
    create_pr(parser.parse_args())
  File "/Users/santiago/scripts/git/lib/create_pr.py", line 207, in create_pr
    handler = create_handler(args)
  File "/Users/santiago/scripts/git/lib/create_pr.py", line 198, in create_handler
    id_type = Helper.branch_id_type()
  File "/Users/santiago/scripts/git/lib/misc/Helper.py", line 180, in branch_id_type
    match = re.search('^(w|r)?(\d+)\-', branch_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py", line 146, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or buffer
```
Using git-scripts version `0.3.0`

**Comment by santi-h** [comment]
I was in a subfolder, not where the `.git` folder is
