### ISSUE TITLE
Issue: [create_pr] GitCommandError: 'git log --format=%B...

### ISSUE THREAD

**Issue by abhishek85** [bodyshopbidsdotcom/git-scripts#280]
```
> git_create_pr -c

Traceback (most recent call last):
  File "/Users/abhishekkumar/GitRepos/git-scripts/lib/run_script.py", line 19, in run
    importlib.import_module(script_name).run()
  File "/Users/abhishekkumar/GitRepos/git-scripts/lib/create_pr.py", line 36, in run
    create_pr(parser.parse_args())
  File "/Users/abhishekkumar/GitRepos/git-scripts/lib/create_pr.py", line 208, in create_pr
    title = (handler.get_title() or '').encode('UTF-8')
  File "/Users/abhishekkumar/GitRepos/git-scripts/lib/create_pr.py", line 90, in get_title
    title = self._get_title()
  File "/Users/abhishekkumar/GitRepos/git-scripts/lib/create_pr.py", line 178, in _get_title
    commit_comments = h2.commit_comments()
  File "/Users/abhishekkumar/GitRepos/git-scripts/lib/misc/helper2.py", line 361, in commit_comments
    for comment in self._git.log(from_branch + '...' + to_branch, format="%B").split('\n'):
  File "/Library/Python/2.7/site-packages/git/cmd.py", line 440, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/git/cmd.py", line 834, in _call_process
    return self.execute(make_call(), **_kwargs)
  File "/Library/Python/2.7/site-packages/git/cmd.py", line 627, in execute
    raise GitCommandError(command, status, stderr_value)
GitCommandError: 'git log --format=%B master...test_to_release' returned with exit code 128
stderr: 'fatal: ambiguous argument 'master...test_to_release': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]''
```
Using git-scripts version `1.2.0`

**Comment by santi-h** [comment]
This happened because `master` was not a branch in his local repo

**Comment by whatisdot** [comment]
@santi-h I've linked clones of this issue. Will your fix resolve these as well?

**Comment by jeet4320** [comment]
Fixed: https://github.com/bodyshopbidsdotcom/git-scripts/pull/385
