### ISSUE TITLE
Issue: [branch_from_task] TypeError: __init__() got an un...

### ISSUE THREAD

**Issue by drc372** [bodyshopbidsdotcom/git-scripts#283]
```
> git_branch_from_task 146077892

Traceback (most recent call last):
  File "/Users/dancolomb/Dropbox_Personal/Projects/Snapsheet/git-scripts/lib/run_script.py", line 19, in run
    importlib.import_module(script_name).run()
  File "/Users/dancolomb/Dropbox (Personal)/Projects/Snapsheet/git-scripts/lib/branch_from_task.py", line 19, in run
    wrike_gateway = Wrike(data_filepath=Helper.get_data_filepath('wrike'), client_id=Helper2.get_var('WRIKE_CLIENT_ID'), client_secret=Helper2.get_var('WRIKE_CLIENT_SECRET'))
TypeError: __init__() got an unexpected keyword argument 'client_secret'
```
Using git-scripts version `2.0.0`

**Comment by santi-h** [comment]
resolved, needed to install pip requirements
