### ISSUE TITLE
Issue: [branch_from_task] TypeError: __init__() got an un...

### ISSUE THREAD

**Issue by lluchez** [bodyshopbidsdotcom/git-scripts#290]
```
> git_branch_from_task https://www.wrike.com/open.htm?id=154469584

Traceback (most recent call last):
  File "/Users/lionelluchez/Snapsheet/Projects/bodyshopbidsdotcom/git-scripts/lib/run_script.py", line 19, in run
    importlib.import_module(script_name).run()
  File "/Users/lionelluchez/Snapsheet/Projects/bodyshopbidsdotcom/git-scripts/lib/branch_from_task.py", line 19, in run
    wrike_gateway = Wrike(data_filepath=Helper.get_data_filepath('wrike'), client_id=Helper2.get_var('WRIKE_CLIENT_ID'), client_secret=Helper2.get_var('WRIKE_CLIENT_SECRET'))
  File "/Library/Python/2.7/site-packages/wrike.py", line 6, in __init__
    OAuth2Gateway.__init__(self, data_filepath=data_filepath, auth_info=auth_info, tokens_updater=tokens_updater)
TypeError: __init__() got an unexpected keyword argument 'tokens_updater'
```
Using git-scripts version `2.1.0`

**Comment by santi-h** [comment]
He had basegateway version 0.10, and it should be version 0.12

The should be added in requirements.txt
