### ISSUE TITLE
Issue: [branch_from_task] TypeError: __init__() got an un...

### ISSUE THREAD

**Issue by jaskiewiczm** [bodyshopbidsdotcom/git-scripts#294]
```
> git_branch_from_task 160617509

Traceback (most recent call last):
  File "/Users/jaskiemr/git-scripts/lib/run_script.py", line 19, in run
    importlib.import_module(script_name).run()
  File "/Users/jaskiemr/git-scripts/lib/branch_from_task.py", line 19, in run
    wrike_gateway = Wrike(data_filepath=Helper.get_data_filepath('wrike'), client_id=Helper2.get_var('WRIKE_CLIENT_ID'), client_secret=Helper2.get_var('WRIKE_CLIENT_SECRET'))
TypeError: __init__() got an unexpected keyword argument 'client_secret'
```
Using git-scripts version `2.0.2`

**Comment by santi-h** [comment]
@jaskiewiczm you need to update git scripts with `git_check_for_updates` and then install the requirements:
- go into the git-scripts directory, and run `sudo pip install -r requirements.txt`
