### ISSUE TITLE
Issue: [label_pr] TypeError: HEAD is a detached symbolic...

### ISSUE THREAD

**Issue by whatisdot** [bodyshopbidsdotcom/git-scripts#322]
```
> git_label_pr Pushing... -q -r

Traceback (most recent call last):
  File "/Users/davidtittle/workspace/git-scripts/lib/run_script.py", line 19, in run
    importlib.import_module(script_name).run()
  File "/Users/davidtittle/workspace/git-scripts/lib/label_pr.py", line 19, in run
    label_pr(parser.parse_args())
  File "/Users/davidtittle/workspace/git-scripts/lib/label_pr.py", line 27, in label_pr
    pr = api.get_pr_from_branch(h2.current_branch())
  File "/Users/davidtittle/workspace/git-scripts/lib/misc/helper2.py", line 155, in current_branch
    return str(self._repo.active_branch)
  File "/Library/Python/2.7/site-packages/git/repo/base.py", line 631, in active_branch
    return self.head.reference
  File "/Library/Python/2.7/site-packages/git/refs/symbolic.py", line 258, in _get_reference
    raise TypeError("%s is a detached symbolic reference as it points to %r" % (self, sha))
TypeError: HEAD is a detached symbolic reference as it points to '369da50a60e99ab7a087c2b01dcef371ae8d254d'
```
Using git-scripts version `2.8.0`

**Comment by whatisdot** [comment]
I got these errors because I am too good at multitasking :)  I was switching branches while the push was underway.

Can we assign the branch name to a variable when the script starts?

**Comment by whatisdot** [comment]
This has been resolved.
