### ISSUE TITLE
Issue: [heroku_push] TypeError: HEAD is a detached symbol...

### ISSUE THREAD

**Issue by NathanShi** [bodyshopbidsdotcom/git-scripts#323]
```
> git_heroku_push stage

Traceback (most recent call last):
  File "/Users/yibingshi/shops/git-scripts/lib/run_script.py", line 19, in run
    importlib.import_module(script_name).run()
  File "/Users/yibingshi/shops/git-scripts/lib/heroku_push.py", line 21, in run
    heroku_push(parser.parse_args())
  File "/Users/yibingshi/shops/git-scripts/lib/heroku_push.py", line 24, in heroku_push
    command = heroku_push_command(args)
  File "/Users/yibingshi/shops/git-scripts/lib/heroku_push.py", line 47, in heroku_push_command
    return HerokuPush(args, h2).command()
  File "/Users/yibingshi/shops/git-scripts/lib/heroku_push.py", line 107, in command
    has_pr = self._pr() is not None
  File "/Users/yibingshi/shops/git-scripts/lib/heroku_push.py", line 54, in wrapper
    cacher._cache[key_name] = original_function(cacher, *args, **kwargs)
  File "/Users/yibingshi/shops/git-scripts/lib/heroku_push.py", line 274, in _pr
    return self._github_api().get_pr_from_branch(self._h2.current_branch())
  File "/Users/yibingshi/shops/git-scripts/lib/misc/helper2.py", line 155, in current_branch
    return str(self._repo.active_branch)
  File "/Library/Python/2.7/site-packages/git/repo/base.py", line 631, in active_branch
    return self.head.reference
  File "/Library/Python/2.7/site-packages/git/refs/symbolic.py", line 258, in _get_reference
    raise TypeError("%s is a detached symbolic reference as it points to %r" % (self, sha))
TypeError: HEAD is a detached symbolic reference as it points to '042f3cffca0cb4f1979ab32bf1cec18eb962c0f9'
```
Using git-scripts version `2.8.0`

**Comment by santi-h** [comment]
@NathanShi Looks like this happened because you were not on a branch?
