### ISSUE TITLE
Issue: [create_pr] GitCommandError: 'git log --format=%B...

### ISSUE THREAD

**Issue by lluchez** [bodyshopbidsdotcom/git-scripts#328]
```
> git_create_pr

Traceback (most recent call last):
  File "/Users/lionelluchez/Snapsheet/Projects/bodyshopbidsdotcom/git-scripts/lib/run_script.py", line 19, in run
    importlib.import_module(script_name).run()
  File "/Users/lionelluchez/Snapsheet/Projects/bodyshopbidsdotcom/git-scripts/lib/create_pr.py", line 36, in run
    create_pr(parser.parse_args())
  File "/Users/lionelluchez/Snapsheet/Projects/bodyshopbidsdotcom/git-scripts/lib/create_pr.py", line 213, in create_pr
    title = (handler.get_title() or '').encode('UTF-8')
  File "/Users/lionelluchez/Snapsheet/Projects/bodyshopbidsdotcom/git-scripts/lib/create_pr.py", line 93, in get_title
    title = self._get_title()
  File "/Users/lionelluchez/Snapsheet/Projects/bodyshopbidsdotcom/git-scripts/lib/create_pr.py", line 181, in _get_title
    commit_comments = h2.commit_comments()
  File "/Users/lionelluchez/Snapsheet/Projects/bodyshopbidsdotcom/git-scripts/lib/misc/helper2.py", line 367, in commit_comments
    for comment in self._git.log(from_branch + '...' + to_branch, format="%B").split('\n'):
  File "/Library/Python/2.7/site-packages/git/cmd.py", line 440, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/git/cmd.py", line 834, in _call_process
    return self.execute(make_call(), **_kwargs)
  File "/Library/Python/2.7/site-packages/git/cmd.py", line 627, in execute
    raise GitCommandError(command, status, stderr_value)
GitCommandError: 'git log --format=%B master...james-river-invoices-api-invoice-types-update' returned with exit code 128
stderr: 'fatal: ambiguous argument 'master...james-river-invoices-api-invoice-types-update': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]''
```
Using git-scripts version `2.8.0`

**Comment by lluchez** [comment]
This happens when the branch hasn't been created with `git_branch_from_xxx`

**Comment by santi-h** [comment]
Branch name: `james-river-invoices-api-invoice-types-update`

**Comment by whatisdot** [comment]
Clone of #280

**Comment by jeet4320** [comment]
Fixed https://github.com/bodyshopbidsdotcom/git-scripts/pull/385
