### ISSUE TITLE
Issue: [heroku_push] TypeError: string indices must be in...

### ISSUE THREAD

**Issue by cswanso2** [bodyshopbidsdotcom/git-scripts#329]
```
> git_heroku_push snapsheet-qa5

Traceback (most recent call last):
  File "/Users/charlesswanson/dev/git-scripts/lib/run_script.py", line 19, in run
    importlib.import_module(script_name).run()
  File "/Users/charlesswanson/dev/git-scripts/lib/heroku_push.py", line 16, in run
    heroku_push(parser.parse_args())
  File "/Users/charlesswanson/dev/git-scripts/lib/heroku_push.py", line 19, in heroku_push
    command = heroku_push_command(args)
  File "/Users/charlesswanson/dev/git-scripts/lib/heroku_push.py", line 42, in heroku_push_command
    return HerokuPush(args, h2).command()
  File "/Users/charlesswanson/dev/git-scripts/lib/heroku_push.py", line 103, in command
    pr_has_qa_label = self._qa_label_from_pr() is not None
  File "/Users/charlesswanson/dev/git-scripts/lib/heroku_push.py", line 49, in wrapper
    cacher._cache[key_name] = original_function(cacher, *args, **kwargs)
  File "/Users/charlesswanson/dev/git-scripts/lib/heroku_push.py", line 282, in _qa_label_from_pr
    for label in (self._github_api().get_labels(pr['number'])[0] or []):
TypeError: string indices must be integers
```
Using git-scripts version `2.8.0`

**Comment by whatisdot** [comment]
@cswanso2 has this been resolved? If so, please close this issue.
