### ISSUE TITLE
Issue: [push_eb] GitCommandError: 'git rev-parse master'...

### ISSUE THREAD

**Issue by degan-snapsheet** [bodyshopbidsdotcom/git-scripts#396]
```
> git_push_eb qa1

Traceback (most recent call last):
  File "/Users/diannak.egan/git-scripts/lib/run_script.py", line 22, in run
    run_script = pre_script(script_name)
  File "/Users/diannak.egan/git-scripts/lib/pre_script.py", line 31, in pre_script
    ret = not check_for_updates(config['days_between_update_checks'])
  File "/Users/diannak.egan/git-scripts/lib/pre_script.py", line 70, in check_for_updates
    ret = update(repo_path, force = True)
  File "/Users/diannak.egan/git-scripts/lib/misc/updater.py", line 60, in update
    local_sha = helper.local_sha(branch = branch)
  File "/Users/diannak.egan/git-scripts/lib/misc/helper2.py", line 236, in local_sha
    return self._git.rev_parse(params['branch'])
  File "/Users/diannak.egan/.virtualenvs/git-scripts/lib/python2.7/site-packages/git/cmd.py", line 440, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/Users/diannak.egan/.virtualenvs/git-scripts/lib/python2.7/site-packages/git/cmd.py", line 834, in _call_process
    return self.execute(make_call(), **_kwargs)
  File "/Users/diannak.egan/.virtualenvs/git-scripts/lib/python2.7/site-packages/git/cmd.py", line 627, in execute
    raise GitCommandError(command, status, stderr_value)
GitCommandError: 'git rev-parse master' returned with exit code 128
stderr: 'fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]''
```
Using git-scripts version `2.24.1`

**Comment by jeet4320** [comment]
https://www.wrike.com/open.htm?id=278177436
